# Generated by Django 6.0.3 on 2026-03-24 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('commit', models.CharField(help_text='Описание изменений', max_length=255, verbose_name='Коммит')),
                ('components_count', models.PositiveIntegerField(default=0, verbose_name='Компоненты')),
                ('status', models.CharField(choices=[('completed', 'Завершено'), ('in_progress', 'В процессе'), ('failed', 'Ошибка')], default='completed', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Генерация',
                'verbose_name_plural': 'Генерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
