# Generated by Django 6.0.3 on 2026-03-24 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='description',
        ),
        migrations.AddField(
            model_name='generation',
            name='commit_hash',
            field=models.CharField(blank=True, max_length=40, verbose_name='Хеш коммита'),
        ),
        migrations.AddField(
            model_name='generation',
            name='commit_message',
            field=models.TextField(blank=True, verbose_name='Сообщение коммита'),
        ),
        migrations.AddField(
            model_name='generation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='generation',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='generation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generations/pdf/', verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='generation',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='generations/word/', verbose_name='Word файл'),
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.CharField(default='main', max_length=100, verbose_name='Ветка'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL репозитория'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub username')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('telegram_notifications', models.BooleanField(default=False, verbose_name='Telegram уведомления')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
