# Generated by Django 4.1.7 on 2026-05-11 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_remove_generation_commit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "projects_limit",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Лимит проектов"
                    ),
                ),
                (
                    "generations_limit",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Лимит генераций в месяц"
                    ),
                ),
                (
                    "word_available",
                    models.BooleanField(default=False, verbose_name="Доступен Word"),
                ),
                (
                    "pdf_available",
                    models.BooleanField(default=True, verbose_name="Доступен PDF"),
                ),
                (
                    "remove_logo",
                    models.BooleanField(
                        default=False, verbose_name="Убрать логотип сервиса"
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, verbose_name="Приоритетная поддержка"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата начала"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
