# Generated by Django 4.1.7 on 2026-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="react_archive",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="react_projects/",
                verbose_name="React архив",
            ),
        ),
    ]
