# Generated by Django 4.1.7 on 2026-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_project_react_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="generation",
            name="instruction_data",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Данные инструкции"
            ),
        ),
    ]
