# Generated by Django 4.1.7 on 2026-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_generation_instruction_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="generation",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Время генерации (сек)"
            ),
        ),
    ]
