# Generated by Django 4.1.7 on 2026-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_generation_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="business_context",
            field=models.TextField(
                blank=True,
                help_text="Для кого эта система, что делают пользователи, какие задачи решает",
                verbose_name="Бизнес-контекст",
            ),
        ),
    ]
