# Generated by Django 4.1.7 on 2026-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_project_business_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="api_token",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Токен для расширения Chrome"
            ),
        ),
    ]
