# Generated by Django 4.1.7 on 2026-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_project_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="backend_archive",
            field=models.FileField(
                blank=True, null=True, upload_to="backends/", verbose_name="ZIP бэкенда"
            ),
        ),
    ]
