# Generated by Django 4.1.7 on 2026-09-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_project_backend_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="app_login",
            field=models.CharField(blank=True, max_length=200, verbose_name="Логин"),
        ),
        migrations.AddField(
            model_name="project",
            name="app_password",
            field=models.CharField(blank=True, max_length=200, verbose_name="Пароль"),
        ),
        migrations.AddField(
            model_name="project",
            name="app_url",
            field=models.CharField(
                blank=True,
                help_text="Например: https://crm.example.com",
                max_length=500,
                verbose_name="URL приложения",
            ),
        ),
    ]
